### ISSUE TITLE
Speeches are included twice in protocol

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/GermaParl2#4]
In session 13/096, some speeches are included twice because they occur twice in the raw data.

**Comment by Freschler** [comment]
A similar issues occurs in 14/069: div type="agenda_item" n="7" what="debate" desc="Erste Beratung des von den Abgeordneten Dr. Guido Westerwelle, Günther Friedrich..."  occurs twice  (cf. n="7" vs. n="8")

**Comment by ChristophLeonhardt** [comment]
Thank you for bringing the issue in 14/069 to our attention.

This issue is addressed for both protocols in the updated version of GermaParl, GermaParl v2.0.1.

I will close this issue for now as the specific issue is solved. However, it is possible that this occurs in other protocols as well. In this case, a new issue should be opened.
