### ISSUE TITLE
4 missing protocols in LP 15

### ISSUE THREAD

**Issue by s-ziegler** [PolMine/GermaParl2#7]
According to the Bundestag website, there were 187 parliamentary sessions in the 15th legislative period, the corpus only contains 183. Minutes for sessions 184-187 (sessions held on 6/30, 7/1, 9/7, and 9/28) appear to be missing (https://github.com/PolMine/GermaParlTEI/tree/main/15).

**Comment by ChristophLeonhardt** [comment]
Thank you for your feedback.

The missing protocols are now included in the corpus, starting with the new version of GermaParl, GermaParl v2.0.1. I will close this issue as completed.
